// A more complete list of countries
export const countries = [
  { name: 'Afghanistan', code: 'af', flag: 'https://flagcdn.com/w40/af.png' },
  { name: 'Albania', code: 'al', flag: 'https://flagcdn.com/w40/al.png' },
  { name: 'Algeria', code: 'dz', flag: 'https://flagcdn.com/w40/dz.png' },
  { name: 'Andorra', code: 'ad', flag: 'https://flagcdn.com/w40/ad.png' },
  { name: 'Angola', code: 'ao', flag: 'https://flagcdn.com/w40/ao.png' },
  { name: 'Argentina', code: 'ar', flag: 'https://flagcdn.com/w40/ar.png' },
  { name: 'Armenia', code: 'am', flag: 'https://flagcdn.com/w40/am.png' },
  { name: 'Australia', code: 'au', flag: 'https://flagcdn.com/w40/au.png' },
  { name: 'Austria', code: 'at', flag: 'https://flagcdn.com/w40/at.png' },
  { name: 'Azerbaijan', code: 'az', flag: 'https://flagcdn.com/w40/az.png' },
  { name: 'Bahamas', code: 'bs', flag: 'https://flagcdn.com/w40/bs.png' },
  { name: 'Bahrain', code: 'bh', flag: 'https://flagcdn.com/w40/bh.png' },
  { name: 'Bangladesh', code: 'bd', flag: 'https://flagcdn.com/w40/bd.png' },
  { name: 'Barbados', code: 'bb', flag: 'https://flagcdn.com/w40/bb.png' },
  { name: 'Belarus', code: 'by', flag: 'https://flagcdn.com/w40/by.png' },
  { name: 'Belgium', code: 'be', flag: 'https://flagcdn.com/w40/be.png' },
  { name: 'Belize', code: 'bz', flag: 'https://flagcdn.com/w40/bz.png' },
  { name: 'Benin', code: 'bj', flag: 'https://flagcdn.com/w40/bj.png' },
  { name: 'Bhutan', code: 'bt', flag: 'https://flagcdn.com/w40/bt.png' },
  { name: 'Bolivia', code: 'bo', flag: 'https://flagcdn.com/w40/bo.png' },
  { name: 'Brazil', code: 'br', flag: 'https://flagcdn.com/w40/br.png' },
  { name: 'Brunei', code: 'bn', flag: 'https://flagcdn.com/w40/bn.png' },
  { name: 'Bulgaria', code: 'bg', flag: 'https://flagcdn.com/w40/bg.png' },
  { name: 'Cambodia', code: 'kh', flag: 'https://flagcdn.com/w40/kh.png' },
  { name: 'Cameroon', code: 'cm', flag: 'https://flagcdn.com/w40/cm.png' },
  { name: 'Canada', code: 'ca', flag: 'https://flagcdn.com/w40/ca.png' },
  { name: 'Chad', code: 'td', flag: 'https://flagcdn.com/w40/td.png' },
  { name: 'Chile', code: 'cl', flag: 'https://flagcdn.com/w40/cl.png' },
  { name: 'China', code: 'cn', flag: 'https://flagcdn.com/w40/cn.png' },
  { name: 'Colombia', code: 'co', flag: 'https://flagcdn.com/w40/co.png' },
  { name: 'Congo', code: 'cg', flag: 'https://flagcdn.com/w40/cg.png' },
  { name: 'Costa Rica', code: 'cr', flag: 'https://flagcdn.com/w40/cr.png' },
  { name: 'Croatia', code: 'hr', flag: 'https://flagcdn.com/w40/hr.png' },
  { name: 'Cuba', code: 'cu', flag: 'https://flagcdn.com/w40/cu.png' },
  { name: 'Cyprus', code: 'cy', flag: 'https://flagcdn.com/w40/cy.png' },
  { name: 'Czech Republic', code: 'cz', flag: 'https://flagcdn.com/w40/cz.png' },
  { name: 'Denmark', code: 'dk', flag: 'https://flagcdn.com/w40/dk.png' },
  { name: 'Egypt', code: 'eg', flag: 'https://flagcdn.com/w40/eg.png' },
  { name: 'Estonia', code: 'ee', flag: 'https://flagcdn.com/w40/ee.png' },
  { name: 'Ethiopia', code: 'et', flag: 'https://flagcdn.com/w40/et.png' },
  { name: 'Fiji', code: 'fj', flag: 'https://flagcdn.com/w40/fj.png' },
  { name: 'Finland', code: 'fi', flag: 'https://flagcdn.com/w40/fi.png' },
  { name: 'France', code: 'fr', flag: 'https://flagcdn.com/w40/fr.png' },
  { name: 'Georgia', code: 'ge', flag: 'https://flagcdn.com/w40/ge.png' },
  { name: 'Germany', code: 'de', flag: 'https://flagcdn.com/w40/de.png' },
  { name: 'Ghana', code: 'gh', flag: 'https://flagcdn.com/w40/gh.png' },
  { name: 'Greece', code: 'gr', flag: 'https://flagcdn.com/w40/gr.png' },
  { name: 'Hungary', code: 'hu', flag: 'https://flagcdn.com/w40/hu.png' },
  { name: 'Iceland', code: 'is', flag: 'https://flagcdn.com/w40/is.png' },
  { name: 'India', code: 'in', flag: 'https://flagcdn.com/w40/in.png' },
  { name: 'Indonesia', code: 'id', flag: 'https://flagcdn.com/w40/id.png' },
  { name: 'Iran', code: 'ir', flag: 'https://flagcdn.com/w40/ir.png' },
  { name: 'Iraq', code: 'iq', flag: 'https://flagcdn.com/w40/iq.png' },
  { name: 'Ireland', code: 'ie', flag: 'https://flagcdn.com/w40/ie.png' },
  { name: 'Israel', code: 'il', flag: 'https://flagcdn.com/w40/il.png' },
  { name: 'Italy', code: 'it', flag: 'https://flagcdn.com/w40/it.png' },
  { name: 'Japan', code: 'jp', flag: 'https://flagcdn.com/w40/jp.png' },
  { name: 'Kenya', code: 'ke', flag: 'https://flagcdn.com/w40/ke.png' },
  { name: 'Kuwait', code: 'kw', flag: 'https://flagcdn.com/w40/kw.png' },
  { name: 'Malaysia', code: 'my', flag: 'https://flagcdn.com/w40/my.png' },
  { name: 'Maldives', code: 'mv', flag: 'https://flagcdn.com/w40/mv.png' },
  { name: 'Mexico', code: 'mx', flag: 'https://flagcdn.com/w40/mx.png' },
  { name: 'Monaco', code: 'mc', flag: 'https://flagcdn.com/w40/mc.png' },
  { name: 'Nepal', code: 'np', flag: 'https://flagcdn.com/w40/np.png' },
  { name: 'Netherlands', code: 'nl', flag: 'https://flagcdn.com/w40/nl.png' },
  { name: 'New Zealand', code: 'nz', flag: 'https://flagcdn.com/w40/nz.png' },
  { name: 'Nigeria', code: 'ng', flag: 'https://flagcdn.com/w40/ng.png' },
  { name: 'North Korea', code: 'kp', flag: 'https://flagcdn.com/w40/kp.png' },
  { name: 'Norway', code: 'no', flag: 'https://flagcdn.com/w40/no.png' },
  { name: 'Oman', code: 'om', flag: 'https://flagcdn.com/w40/om.png' },
  { name: 'Pakistan', code: 'pk', flag: 'https://flagcdn.com/w40/pk.png' },
  { name: 'Peru', code: 'pe', flag: 'https://flagcdn.com/w40/pe.png' },
  { name: 'Philippines', code: 'ph', flag: 'https://flagcdn.com/w40/ph.png' },
  { name: 'Poland', code: 'pl', flag: 'https://flagcdn.com/w40/pl.png' },
  { name: 'Portugal', code: 'pt', flag: 'https://flagcdn.com/w40/pt.png' },
  { name: 'Qatar', code: 'qa', flag: 'https://flagcdn.com/w40/qa.png' },
  { name: 'Russia', code: 'ru', flag: 'https://flagcdn.com/w40/ru.png' },
  { name: 'Saudi Arabia', code: 'sa', flag: 'https://flagcdn.com/w40/sa.png' },
  { name: 'Singapore', code: 'sg', flag: 'https://flagcdn.com/w40/sg.png' },
  { name: 'South Africa', code: 'za', flag: 'https://flagcdn.com/w40/za.png' },
  { name: 'South Korea', code: 'kr', flag: 'https://flagcdn.com/w40/kr.png' },
  { name: 'Spain', code: 'es', flag: 'https://flagcdn.com/w40/es.png' },
  { name: 'Sri Lanka', code: 'lk', flag: 'https://flagcdn.com/w40/lk.png' },
  { name: 'Sweden', code: 'se', flag: 'https://flagcdn.com/w40/se.png' },
  { name: 'Switzerland', code: 'ch', flag: 'https://flagcdn.com/w40/ch.png' },
  { name: 'Thailand', code: 'th', flag: 'https://flagcdn.com/w40/th.png' },
  { name: 'Turkey', code: 'tr', flag: 'https://flagcdn.com/w40/tr.png' },
  { name: 'United Arab Emirates', code: 'ae', flag: 'https://flagcdn.com/w40/ae.png' },
  { name: 'United Kingdom', code: 'gb', flag: 'https://flagcdn.com/w40/gb.png' },
  { name: 'United States', code: 'us', flag: 'https://flagcdn.com/w40/us.png' },
  { name: 'Vietnam', code: 'vn', flag: 'https://flagcdn.com/w40/vn.png' },
];