// A more complete list of countries without 'code'
export const countries = [
  { name: 'Afghanistan', flag: 'https://flagcdn.com/w40/af.png' },
  { name: 'Albania', flag: 'https://flagcdn.com/w40/al.png' },
  { name: 'Algeria', flag: 'https://flagcdn.com/w40/dz.png' },
  { name: 'Andorra', flag: 'https://flagcdn.com/w40/ad.png' },
  { name: 'Angola', flag: 'https://flagcdn.com/w40/ao.png' },
  { name: 'Argentina', flag: 'https://flagcdn.com/w40/ar.png' },
  { name: 'Armenia', flag: 'https://flagcdn.com/w40/am.png' },
  { name: 'Australia', flag: 'https://flagcdn.com/w40/au.png' },
  { name: 'Austria', flag: 'https://flagcdn.com/w40/at.png' },
  { name: 'Azerbaijan', flag: 'https://flagcdn.com/w40/az.png' },
  { name: 'Bahamas', flag: 'https://flagcdn.com/w40/bs.png' },
  { name: 'Bahrain', flag: 'https://flagcdn.com/w40/bh.png' },
  { name: 'Bangladesh', flag: 'https://flagcdn.com/w40/bd.png' },
  { name: 'Barbados', flag: 'https://flagcdn.com/w40/bb.png' },
  { name: 'Belarus', flag: 'https://flagcdn.com/w40/by.png' },
  { name: 'Belgium', flag: 'https://flagcdn.com/w40/be.png' },
  { name: 'Belize', flag: 'https://flagcdn.com/w40/bz.png' },
  { name: 'Benin', flag: 'https://flagcdn.com/w40/bj.png' },
  { name: 'Bhutan', flag: 'https://flagcdn.com/w40/bt.png' },
  { name: 'Bolivia', flag: 'https://flagcdn.com/w40/bo.png' },
  { name: 'Brazil', flag: 'https://flagcdn.com/w40/br.png' },
  { name: 'Brunei', flag: 'https://flagcdn.com/w40/bn.png' },
  { name: 'Bulgaria', flag: 'https://flagcdn.com/w40/bg.png' },
  { name: 'Cambodia', flag: 'https://flagcdn.com/w40/kh.png' },
  { name: 'Cameroon', flag: 'https://flagcdn.com/w40/cm.png' },
  { name: 'Canada', flag: 'https://flagcdn.com/w40/ca.png' },
  { name: 'Chad', flag: 'https://flagcdn.com/w40/td.png' },
  { name: 'Chile', flag: 'https://flagcdn.com/w40/cl.png' },
  { name: 'China', flag: 'https://flagcdn.com/w40/cn.png' },
  { name: 'Colombia', flag: 'https://flagcdn.com/w40/co.png' },
  { name: 'Congo', flag: 'https://flagcdn.com/w40/cg.png' },
  { name: 'Costa Rica', flag: 'https://flagcdn.com/w40/cr.png' },
  { name: 'Croatia', flag: 'https://flagcdn.com/w40/hr.png' },
  { name: 'Cuba', flag: 'https://flagcdn.com/w40/cu.png' },
  { name: 'Cyprus', flag: 'https://flagcdn.com/w40/cy.png' },
  { name: 'Czech Republic', flag: 'https://flagcdn.com/w40/cz.png' },
  { name: 'Denmark', flag: 'https://flagcdn.com/w40/dk.png' },
  { name: 'Egypt', flag: 'https://flagcdn.com/w40/eg.png' },
  { name: 'Estonia', flag: 'https://flagcdn.com/w40/ee.png' },
  { name: 'Ethiopia', flag: 'https://flagcdn.com/w40/et.png' },
  { name: 'Fiji', flag: 'https://flagcdn.com/w40/fj.png' },
  { name: 'Finland', flag: 'https://flagcdn.com/w40/fi.png' },
  { name: 'France', flag: 'https://flagcdn.com/w40/fr.png' },
  { name: 'Georgia', flag: 'https://flagcdn.com/w40/ge.png' },
  { name: 'Germany', flag: 'https://flagcdn.com/w40/de.png' },
  { name: 'Ghana', flag: 'https://flagcdn.com/w40/gh.png' },
  { name: 'Greece', flag: 'https://flagcdn.com/w40/gr.png' },
  { name: 'Hungary', flag: 'https://flagcdn.com/w40/hu.png' },
  { name: 'Iceland', flag: 'https://flagcdn.com/w40/is.png' },
  { name: 'India', flag: 'https://flagcdn.com/w40/in.png' },
  { name: 'Indonesia', flag: 'https://flagcdn.com/w40/id.png' },
  { name: 'Iran', flag: 'https://flagcdn.com/w40/ir.png' },
  { name: 'Iraq', flag: 'https://flagcdn.com/w40/iq.png' },
  { name: 'Ireland', flag: 'https://flagcdn.com/w40/ie.png' },
  { name: 'Israel', flag: 'https://flagcdn.com/w40/il.png' },
  { name: 'Italy', flag: 'https://flagcdn.com/w40/it.png' },
  { name: 'Japan', flag: 'https://flagcdn.com/w40/jp.png' },
  { name: 'Kenya', flag: 'https://flagcdn.com/w40/ke.png' },
  { name: 'Kuwait', flag: 'https://flagcdn.com/w40/kw.png' },
  { name: 'Malaysia', flag: 'https://flagcdn.com/w40/my.png' },
  { name: 'Maldives', flag: 'https://flagcdn.com/w40/mv.png' },
  { name: 'Mexico', flag: 'https://flagcdn.com/w40/mx.png' },
  { name: 'Monaco', flag: 'https://flagcdn.com/w40/mc.png' },
  { name: 'Nepal', flag: 'https://flagcdn.com/w40/np.png' },
  { name: 'Netherlands', flag: 'https://flagcdn.com/w40/nl.png' },
  { name: 'New Zealand', flag: 'https://flagcdn.com/w40/nz.png' },
  { name: 'Nigeria', flag: 'https://flagcdn.com/w40/ng.png' },
  { name: 'North Korea', flag: 'https://flagcdn.com/w40/kp.png' },
  { name: 'Norway', flag: 'https://flagcdn.com/w40/no.png' },
  { name: 'Oman', flag: 'https://flagcdn.com/w40/om.png' },
  { name: 'Pakistan', flag: 'https://flagcdn.com/w40/pk.png' },
  { name: 'Peru', flag: 'https://flagcdn.com/w40/pe.png' },
  { name: 'Philippines', flag: 'https://flagcdn.com/w40/ph.png' },
  { name: 'Poland', flag: 'https://flagcdn.com/w40/pl.png' },
  { name: 'Portugal', flag: 'https://flagcdn.com/w40/pt.png' },
  { name: 'Qatar', flag: 'https://flagcdn.com/w40/qa.png' },
  { name: 'Russia', flag: 'https://flagcdn.com/w40/ru.png' },
  { name: 'Saudi Arabia', flag: 'https://flagcdn.com/w40/sa.png' },
  { name: 'Singapore', flag: 'https://flagcdn.com/w40/sg.png' },
  { name: 'South Africa', flag: 'https://flagcdn.com/w40/za.png' },
  { name: 'South Korea', flag: 'https://flagcdn.com/w40/kr.png' },
  { name: 'Spain', flag: 'https://flagcdn.com/w40/es.png' },
  { name: 'Sri Lanka', flag: 'https://flagcdn.com/w40/lk.png' },
  { name: 'Sweden', flag: 'https://flagcdn.com/w40/se.png' },
  { name: 'Switzerland', flag: 'https://flagcdn.com/w40/ch.png' },
  { name: 'Thailand', flag: 'https://flagcdn.com/w40/th.png' },
  { name: 'Turkey', flag: 'https://flagcdn.com/w40/tr.png' },
  { name: 'United Arab Emirates', flag: 'https://flagcdn.com/w40/ae.png' },
  { name: 'United Kingdom', flag: 'https://flagcdn.com/w40/gb.png' },
  { name: 'United States', flag: 'https://flagcdn.com/w40/us.png' },
  { name: 'Vietnam', flag: 'https://flagcdn.com/w40/vn.png' },
];
